default: &default
  pool: <%= ENV['DB_POOL'] || 5 %>
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password:
  database: sample_rails_clean_architecture
  encoding: utf8

test:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password:
  database: sample_rails_clean_architecture_test

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  encoding: utf8